server:
  port: 8081

spring:
  data:
   mongodb:
     uri: mongodb+srv://unikyadav:techHire12345@cluster0.csuvc.mongodb.net/?retryWrites=true&w=majority
     database: TechHireDB



  security:
     oauth2:
       resource-server:
         jwt:
           issuer-uri: http://localhost:8080/realms/TechHire
           jwk-set-uri: http://localhost:8080/realms/TechHire/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080
  realm: TechHire
  resource: techhire-backend
  credentials:
    secret: sov5dBqt5XSqMEaTK9YXafmPsUsIqLAi
  ssl-required: external
  bearer-only: true
  use-resource-role-mappings: true
