package com.example.TechHire.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "applications") // Collection name in MongoDB
@Data
public class Application {

    @Id
    private String id; // Auto-generated by MongoDB

    private String candidateId; // Fetched from candidate profile
    private String jobId;       // Fetched from job posting
    private String status;       // Pending, Shortlisted, Rejected, Hired
}
