package com.example.TechHire.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

@Document(collection = "shortlist_candidate")
@Data
public class ShortlistCandidate {
    @Id
    private String id; // Auto-generated by MongoDB
    private String jobAppliedId; // Added to track which application was shortlisted
    private String candidateId;
    private String appliedFor;
    private String jobId;
    private String status; // Always "Shortlisted"
    private String candidateName;
    private String candidateEmail;
    private String resumeUrl;
    private String phoneNumber;
    private LocalDate appliedDate;

    public ShortlistCandidate(String jobAppliedId, String candidateId,String jobId, String appliedFor ,String candidateName, String candidateEmail, String resumeUrl,String phoneNumber) {
        this.jobAppliedId = jobAppliedId;
        this.candidateId = candidateId;
        this.jobId = jobId;
        this.appliedFor = appliedFor;
        this.candidateName = candidateName;
        this.candidateEmail = candidateEmail;
        this.resumeUrl = resumeUrl;
        this.phoneNumber=phoneNumber;
        this.status = "Shortlisted";
        this.appliedDate = LocalDate.now();
    }
}
